### ISSUE TITLE
Full code for reproducing the resutls

### ISSUE THREAD

**Issue by LeiBAI** [XinshaoAmosWang/ProSelfLC-CVPR2021#3]
Thanks for your excellent work. May I ask whether the full code will be released for reproducing the results and developing new methods based on your work?

Regards

Lei

**Comment by xinshao-wang** [comment]
No problem. I will work on it. Thanks for your interest.

**Comment by LeiBAI** [comment]
Dear Xinshao,

Thank you so much

Cheers

Lei

**Comment by XinshaoAmosWang** [comment]
@LeiBAI , please check the released full code. Thanks.

**Comment by LeiBAI** [comment]
Thank you so much. 

Regards

Lei
